- name: "Coping files"
  become: true
  copy:
    src: /root/project/backend.tar
    dest: /home/ubuntu/

- name: "un-tar"
  become: true
  shell: |
    tar -xvf backend.tar
- name: "installing nodejs modules"
  become: true
  shell: |
    cd backend/
    npm i
- name: "build node"
  become: true
  shell: |
    cd backend/
    npm run build
    
- name: "Start server"
  become: true
  shell: |
    cd backend/
    pm2 start npm --name backend -- start --port 3100