- name: "Coping files"
  copy:
    src: /root/project/backend.tar
    dest: /home/ubuntu/

- name: "un-tar"
  shell: |
    tar -xvf backend.tar
- name: "installing nodejs modules"
  shell: |
    cd backend/
    sudo npm install
    pm2 stop default
    pm2 start npm -- start